### ISSUE TITLE
Wrong broadcast address retrieved when multiple IPs configured on the same interface

### ISSUE THREAD

**Issue by shunf4** [Tans5/tFileTransfer_desktop#1]
https://github.com/Tans5/tFileTransfer_desktop/blob/a1def7fb248ff6c661d7a86ffd222659bca8e21a/net/src/main/java/com/tans/tfiletransporter/netty/AddressUtils.kt#L10-L19

This possibly retrieves a wrong broadcast address (unmatches the selected IP) when the network interface is configured with multiple IP addresses. Then because the broadcast packet is sent to an incorrect destination, the other device is unable to discover current device.

For example, my configuration is as below and that's what happened:

![image](https://github.com/Tans5/tFileTransfer_desktop/assets/20991618/655a571f-f0b3-4550-8fd1-89bc3a9b7b23)

**Comment by Tans5** [comment]
Thanks for your report, I will check it. @shunf4

**Comment by Tans5** [comment]
Could you check this [commit](https://github.com/Tans5/tFileTransfer_desktop/commit/0a668360161fc890b611998df83996c054b5b419) is work? @shunf4

**Comment by shunf4** [comment]
Android client seems successful finding the desktop PC's server now, but after I tap on the server entry, the connection doesn't succeed, with a toast saying only "Error". 

![](https://github.com/Tans5/tFileTransfer_desktop/assets/20991618/5d3c1a40-399f-4018-b329-ad04292c146a)

**Comment by Tans5** [comment]
> Android client seems successful finding the desktop PC's server now, but after I tap on the server entry, the connection doesn't succeed, with a toast saying only "Error".
> 
> ![](https://user-images.githubusercontent.com/20991618/237696204-5d3c1a40-399f-4018-b329-ad04292c146a.jpg)

I also met this problem on low quality network. I am using UDP broadcast + UDP server now, maybe I should use UDP broadcast + TCP server.

**Comment by shunf4** [comment]
Never mind, it's Windows Firewall. Applied proper settings to the firewall and everything worked. Thanks!
