### ISSUE TITLE
.exe : language missing , .jar : JRE version unknown

### ISSUE THREAD

**Issue by itsbrody** [Tans5/tFileTransfer_desktop#2]
Hi,
through research in FDroid Appstore I stumbled over your tool for android devices and  the hint to the adequate desktop APP.
I downloaded that (either as .jar - I know that this would need a Java JVM/JRE) and as (windows) .exe file.

When starting the first one, I didn't get any adequate error message, I can handle; thus - which JRE version is needed (if I'm right with my assumption). The latter did start, but presented itself with a for me unknown language (and this wasn't englisch) - could you help?

Thanks in advance.

**Comment by Tans5** [comment]
You could try JRE 16 and choose [jar application](https://github.com/Tans5/tFileTransfer_desktop/releases/download/v2.0.0/tFileTransfer-windows-x64-2.0.0.jar) to use.  
Use `java -jar tFileTransfer-windows-x64-2.0.0.jar` command to start application.

**Comment by itsbrody** [comment]
Would this then display (at least) in english?

 
 

Gesendet: Donnerstag, 18. Mai 2023 um 10:16 Uhr
Von: "Tans5" ***@***.***>
An: "Tans5/tFileTransfer_desktop" ***@***.***>
Cc: "Wolfgang" ***@***.***>, "Author" ***@***.***>
Betreff: Re: [Tans5/tFileTransfer_desktop] .exe : language missing , .jar : JRE version unknown (Issue #2)


 

You could try JRE 16 and choose jar application to use.
Use java -jar tFileTransfer-windows-x64-2.0.0.jar command to start application.

**Comment by itsbrody** [comment]
Would this then display (at least) in english?


 

BTW: I was able to update JRE8 to latest, but I'm not able to find a (free) JRE16. Would you help me?

 

Gesendet: Donnerstag, 18. Mai 2023 um 10:16 Uhr
Von: "Tans5" ***@***.***>
An: "Tans5/tFileTransfer_desktop" ***@***.***>
Cc: "Wolfgang" ***@***.***>, "Author" ***@***.***>
Betreff: Re: [Tans5/tFileTransfer_desktop] .exe : language missing , .jar : JRE version unknown (Issue #2)


 

You could try JRE 16 and choose jar application to use.
Use java -jar tFileTransfer-windows-x64-2.0.0.jar command to start application.

**Comment by Tans5** [comment]
https://www.oracle.com/java/technologies/javase/jdk16-archive-downloads.html
Choose `Windows x64 Installer` may be ok.

**Comment by itsbrody** [comment]
This needs a registration - I don't want give any company all of my data anyway.

 
 

Gesendet: Donnerstag, 18. Mai 2023 um 11:03 Uhr
Von: "Tans5" ***@***.***>
An: "Tans5/tFileTransfer_desktop" ***@***.***>
Cc: "Wolfgang" ***@***.***>, "Author" ***@***.***>
Betreff: Re: [Tans5/tFileTransfer_desktop] .exe : language missing , .jar : JRE version unknown (Issue #2)


 

https://www.oracle.com/java/technologies/javase/jdk16-archive-downloads.html
Choose Windows x64 Installer may be ok.

**Comment by Tans5** [comment]
Try this: https://download.java.net/openjdk/jdk16/ri/openjdk-16+36_windows-x64_bin.zip

**Comment by Tans5** [comment]
You need add jdk `bin` folder to envirament.

**Comment by itsbrody** [comment]
Thank you very much - this works and tFileTransfer is starting on my windows laptop.

 

Generelly its working, but windows desktop version lacks of navigation possibilities inside the UI. I can only see and deeper navigate into the first part of the displayed directory tree. Any idea?

 

 

 
 

Gesendet: Donnerstag, 18. Mai 2023 um 11:20 Uhr
Von: "Tans5" ***@***.***>
An: "Tans5/tFileTransfer_desktop" ***@***.***>
Cc: "Wolfgang" ***@***.***>, "Author" ***@***.***>
Betreff: Re: [Tans5/tFileTransfer_desktop] .exe : language missing , .jar : JRE version unknown (Issue #2)


 

Try this: https://download.java.net/openjdk/jdk16/ri/openjdk-16+36_windows-x64_bin.zip
