### ISSUE TITLE
missing navigation sliders for bigger directories

### ISSUE THREAD

**Issue by itsbrody** [Tans5/tFileTransfer_desktop#3]
While on Android I'm able to navigate through a big directory tree my drag and hold, I've no such possibility in the windows desktop version. Thus, I'm only able to go into the first 9 sub directories of the users home (remote and local side).

Any idea?

**Comment by Tans5** [comment]
You mean need feature that view different disks' directory on Windows devices ?

**Comment by itsbrody** [comment]
No, herein I miss to be able to navigate, when a directory has more then nine entries of directories and files - I can't reach the "lower" ones.

**Comment by Tans5** [comment]
Could you provide some screenshots?

**Comment by itsbrody** [comment]
attached one screenshot
