### ISSUE TITLE
WI-FI 直连 / WI-FI P2P

### ISSUE THREAD

**Issue by Li-Jinyuan** [Tans5/tFileTransfer_desktop#4]
您好，请问下一步有没有在mac/win上支持 WI-FI 直连 / WI-FI P2P 的计划呢？在安卓客户端上我看到了该功能，但是没有在desktop上发现该功能。请问是mac/pc上缺失类似的开发文档吗？

**Comment by Tans5** [comment]
Compose 是没有 WIFI 的 API 的，这是一个跨平台的 UI 框架，这个做不了，要桌面版也支持 WIFI P2P 我估计要桌面版的原生开发，原生开发我做不了。

**Comment by Li-Jinyuan** [comment]
好的，了解了，谢谢
